### ISSUE TITLE
Task Delegation for Phase I

### ISSUE THREAD

**Issue by thoat** [sweet-spr18/feasta#1]
Hey all, since we can't discuss face-to-face over the break, and since we've all had experience translating Project Description to Functional and Non-functional Requirements in the exam, I suggest the following approach for Phase I:

- [ ] Each of us (myself included) will try our best to translate the stuff on GitHub's [README](https://github.com/sweet-spr18/feasta/blob/master/phase1/README.md) to the following items, and I can compare and aggregate them to a final version. This way, we can make sure everyone is familiar and on the same page with the features we're gonna build. Right now it seems like we still have a bit discrepancies in our understanding of the features, the user flow, etc.

- The items are:

**I. System Features:**
For each feature, try your best to write out the:

> **--Feature Name--**
> a. Description and Priority
> b. Stimulus/Response Sequences
> c. Functional Requirements:
> REQ-1: ...
> REQ-2: ...
> ...
> REQ-n: ...

**II. Non-functional Requirements:** 
(try your best to come up with sth for each category, we'll use each other's knowledge to fill in the gap. To understand what "safety", "security", and "legal" requirements mean, see the [doc](https://docs.google.com/document/d/1cjry2Gvy-nYeNrrhirxqenPDAA9xrtVraQ98jB8VXe8/edit?usp=sharing) or Google)

> - User interfaces
> - Performance
> - Safety
> - Security
> - Legal 

If you disagree with my suggested approach, or have a better idea, let us all know by leaving a comment.

- The other sections in the Phase I paper have been divided on the [doc](https://docs.google.com/document/d/1cjry2Gvy-nYeNrrhirxqenPDAA9xrtVraQ98jB8VXe8/edit?usp=sharing). If you prefer other sections, let me know. 

- [x] @huangjing8798 would you mind starting the PowerPoint?
- [x] @cjag96 would you mind uploading the ppt to GitHub in folder [phase1](https://github.com/sweet-spr18/feasta/tree/master/phase1)? It's best if you can save it as a pdf before uploading.
- [ ] @JPMORIN33 and @amota511 can you do the similar thing with the 2 files you submitted on Blackboard?

-Thoa

**Comment by cjag96** [comment]
Love your organizational skills, Thoa. Thank you!
I did my parts in the analysis, uploaded the ppt PDF and started a draft for the system features (in phase 1 folder). I tried to do most of them, will finish it after the break. I also have to research the safety, security and legal requirements because I think we will definitely have some safety and legal issues.
